sl4j dependency compile-only.
Based on pull request feedback do the following:
- Make slf4j dependency compile-only.
- Put double quotes around dependencies (which are GStrings).

Note that the groovy-all version must match the version used by
'compile gradleApi()' in the gradle-plugin.gradle file. Otherwise
an exception such as the following will occur:
  groovy.lang.GroovyRuntimeException: Conflicting module versions. Module
  groovy-all is loaded in version 2.4.15 and you are trying to load version
  2.4.16