Correct dependencies for hamcrest.
There is an issue when there is a hamcrest mismatch, which should produce a
readable error message, such as:
  Expected: is <10> but: was <9>
but because of incompatabilities between the versions of hamcrest brought in
by junit and mockito, instead there is:
  java.lang.NoSuchMethodError: org.hamcrest.Matcher.describeMismatch(Ljava/lang/Object;Lorg/hamcrest/Description;)V

One solution is described at:
  https://tedvinke.wordpress.com/2013/12/17/mixing-junit-hamcrest-and-mockito-explaining-nosuchmethoderror/

which could be provided by introducing the following dependency:
    testCompile org.mockito:mockito-core:1.10.19, {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }

but the solution of upgrading the hamcrest-core and mockito-core to the latest
version seems to solve the problem as well.